# render.yaml
services:
  - type: web
    name: logies-edges-api
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: logies-edges-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: https://logies-edges-site.vercel.app,http://localhost:5173
      - key: ENV
        value: production
      # Add your keys below in the Render UI after the first deploy:
      - key: GRIDIRON_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false

databases:
  - name: logies-edges-db
    plan: free