"""add premium + tipster subs + player prop models

Revision ID: 0256e130d436
Revises: 4b881a2da1be
Create Date: 2025-11-20 00:35:09.409638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0256e130d436'
down_revision: Union[str, Sequence[str], None] = '4b881a2da1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_prop_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_odds_id', sa.Integer(), nullable=True),
    sa.Column('model_source', sa.String(), nullable=False),
    sa.Column('prob', sa.Float(), nullable=False),
    sa.Column('fair_price', sa.Float(), nullable=False),
    sa.Column('edge', sa.Float(), nullable=False),
    sa.Column('is_premium_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_odds_id'], ['player_odds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_prop_models_created_at'), 'player_prop_models', ['created_at'], unique=False)
    op.create_index(op.f('ix_player_prop_models_player_odds_id'), 'player_prop_models', ['player_odds_id'], unique=False)
    op.add_column('tipster_picks', sa.Column('is_premium_only', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('premium_activated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'premium_activated_at')
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('tipster_picks', 'is_premium_only')
    op.drop_index(op.f('ix_player_prop_models_player_odds_id'), table_name='player_prop_models')
    op.drop_index(op.f('ix_player_prop_models_created_at'), table_name='player_prop_models')
    op.drop_table('player_prop_models')
    # ### end Alembic commands ###
