"""tipster application

Revision ID: 08ed00e4651e
Revises: b7f0911db297
Create Date: 2025-11-27 16:39:33.567680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ed00e4651e'
down_revision: Union[str, Sequence[str], None] = 'b7f0911db297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipster_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('sport_focus', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('admin_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipster_applications_created_at'), 'tipster_applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_tipster_applications_email'), 'tipster_applications', ['email'], unique=False)
    op.create_index(op.f('ix_tipster_applications_firebase_uid'), 'tipster_applications', ['firebase_uid'], unique=False)
    op.create_index(op.f('ix_tipster_applications_id'), 'tipster_applications', ['id'], unique=False)
    op.create_index(op.f('ix_tipster_applications_username'), 'tipster_applications', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipster_applications_username'), table_name='tipster_applications')
    op.drop_index(op.f('ix_tipster_applications_id'), table_name='tipster_applications')
    op.drop_index(op.f('ix_tipster_applications_firebase_uid'), table_name='tipster_applications')
    op.drop_index(op.f('ix_tipster_applications_email'), table_name='tipster_applications')
    op.drop_index(op.f('ix_tipster_applications_created_at'), table_name='tipster_applications')
    op.drop_table('tipster_applications')
    # ### end Alembic commands ###
