"""add provider_league_id to fixtures

Revision ID: 0c886713fb66
Revises: 1d28637135cd
Create Date: 2025-09-18 16:51:52.505235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c886713fb66'
down_revision: Union[str, Sequence[str], None] = '1d28637135cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('provider_home_team_id', sa.Integer(), nullable=True))
    op.add_column('fixtures', sa.Column('provider_away_team_id', sa.Integer(), nullable=True))
    op.add_column('fixtures', sa.Column('provider_league_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_fixtures_provider_away_team_id'), 'fixtures', ['provider_away_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_provider_home_team_id'), 'fixtures', ['provider_home_team_id'], unique=False)
    op.create_index(op.f('ix_fixtures_provider_league_id'), 'fixtures', ['provider_league_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixtures_provider_league_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_provider_home_team_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_provider_away_team_id'), table_name='fixtures')
    op.drop_column('fixtures', 'provider_league_id')
    op.drop_column('fixtures', 'provider_away_team_id')
    op.drop_column('fixtures', 'provider_home_team_id')
    # ### end Alembic commands ###
