"""tipster subscription updates

Revision ID: 14681aede4f1
Revises: 1f6650782874
Create Date: 2025-11-25 13:15:21.327829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14681aede4f1'
down_revision: Union[str, Sequence[str], None] = '1f6650782874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipster_picks', sa.Column('is_subscriber_only', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipster_picks', 'is_subscriber_only')
    # ### end Alembic commands ###
