"""add acca_tickets and acca_legs tables

Revision ID: 16320a3a8f82
Revises: cd103b2b7e1a
Create Date: 2025-10-24 20:20:49.368784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16320a3a8f82'
down_revision: Union[str, Sequence[str], None] = 'cd103b2b7e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
