"""tipster subscription updates

Revision ID: 1f6650782874
Revises: 5158371455f2
Create Date: 2025-11-25 12:16:33.955825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6650782874'
down_revision: Union[str, Sequence[str], None] = '5158371455f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipsters', sa.Column('owner_user_id', sa.BigInteger(), nullable=True))
    op.add_column('tipsters', sa.Column('stripe_account_id', sa.String(), nullable=True))
    op.add_column('tipsters', sa.Column('default_price_cents', sa.Integer(), nullable=True))
    op.add_column('tipsters', sa.Column('currency', sa.String(), nullable=False))
    op.add_column('tipsters', sa.Column('subscriber_limit', sa.Integer(), nullable=True))
    op.add_column('tipsters', sa.Column('is_open_for_new_subs', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_tipsters_owner_user_id'), 'tipsters', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_tipsters_stripe_account_id'), 'tipsters', ['stripe_account_id'], unique=False)
    op.create_foreign_key(None, 'tipsters', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tipsters', type_='foreignkey')
    op.drop_index(op.f('ix_tipsters_stripe_account_id'), table_name='tipsters')
    op.drop_index(op.f('ix_tipsters_owner_user_id'), table_name='tipsters')
    op.drop_column('tipsters', 'is_open_for_new_subs')
    op.drop_column('tipsters', 'subscriber_limit')
    op.drop_column('tipsters', 'currency')
    op.drop_column('tipsters', 'default_price_cents')
    op.drop_column('tipsters', 'stripe_account_id')
    op.drop_column('tipsters', 'owner_user_id')
    # ### end Alembic commands ###
