"""tipster followers

Revision ID: 23ae18175542
Revises: dd07485cc5f8
Create Date: 2025-11-13 23:03:00.887041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ae18175542'
down_revision: Union[str, Sequence[str], None] = 'dd07485cc5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipster_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipster_id', sa.Integer(), nullable=False),
    sa.Column('follower_email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tipster_id'], ['tipsters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipster_follows_follower_email'), 'tipster_follows', ['follower_email'], unique=False)
    op.create_index(op.f('ix_tipster_follows_tipster_id'), 'tipster_follows', ['tipster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipster_follows_tipster_id'), table_name='tipster_follows')
    op.drop_index(op.f('ix_tipster_follows_follower_email'), table_name='tipster_follows')
    op.drop_table('tipster_follows')
    # ### end Alembic commands ###
