"""fixture lockdown

Revision ID: 2cecefa30d7a
Revises: 784d82e88c1d
Create Date: 2025-12-04 23:11:19.381433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cecefa30d7a'
down_revision: Union[str, Sequence[str], None] = '784d82e88c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_fixture_access',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fixture_id', name='uq_user_fixture_access')
    )
    op.create_index(op.f('ix_user_fixture_access_created_at'), 'user_fixture_access', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_fixture_access_day'), 'user_fixture_access', ['day'], unique=False)
    op.create_index(op.f('ix_user_fixture_access_fixture_id'), 'user_fixture_access', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_user_fixture_access_user_id'), 'user_fixture_access', ['user_id'], unique=False)
    op.create_index('ix_userfixtureaccess_user_day', 'user_fixture_access', ['user_id', 'day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_userfixtureaccess_user_day', table_name='user_fixture_access')
    op.drop_index(op.f('ix_user_fixture_access_user_id'), table_name='user_fixture_access')
    op.drop_index(op.f('ix_user_fixture_access_fixture_id'), table_name='user_fixture_access')
    op.drop_index(op.f('ix_user_fixture_access_day'), table_name='user_fixture_access')
    op.drop_index(op.f('ix_user_fixture_access_created_at'), table_name='user_fixture_access')
    op.drop_table('user_fixture_access')
    # ### end Alembic commands ###
