"""tipster fixes

Revision ID: 2ef8d00d6494
Revises: 6058d239ec7e
Create Date: 2025-11-05 23:20:02.508931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef8d00d6494'
down_revision: Union[str, Sequence[str], None] = '6058d239ec7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acca_legs', 'away_name')
    op.drop_column('acca_legs', 'home_name')
    op.create_index(op.f('ix_acca_tickets_source'), 'acca_tickets', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acca_tickets_source'), table_name='acca_tickets')
    op.add_column('acca_legs', sa.Column('home_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('acca_legs', sa.Column('away_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
