"""Add strength field to team_form

Revision ID: 3270049c3b81
Revises: 339054d67b69
Create Date: 2025-09-10 23:22:32.688741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3270049c3b81'
down_revision: Union[str, Sequence[str], None] = '339054d67b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_form', sa.Column('strength', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_form', 'strength')
    # ### end Alembic commands ###
