"""users + follows + user_bets + tipster_subscriptions

Revision ID: 36a8d5b91acd
Revises: e54eb258fc75
Create Date: 2025-11-05 10:14:38.937683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a8d5b91acd'
down_revision: Union[str, Sequence[str], None] = 'e54eb258fc75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('tipster_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tipster_id'], ['tipsters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index('ix_users_uid_email', 'users', ['firebase_uid', 'email'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_table('tipster_subscriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tipster_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_sub_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('renews_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tipster_id'], ['tipsters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tipster_id', name='uq_user_tipster_sub')
    )
    op.create_index('ix_subs_status', 'tipster_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_tipster_subscriptions_renews_at'), 'tipster_subscriptions', ['renews_at'], unique=False)
    op.create_index(op.f('ix_tipster_subscriptions_started_at'), 'tipster_subscriptions', ['started_at'], unique=False)
    op.create_index(op.f('ix_tipster_subscriptions_tipster_id'), 'tipster_subscriptions', ['tipster_id'], unique=False)
    op.create_index(op.f('ix_tipster_subscriptions_user_id'), 'tipster_subscriptions', ['user_id'], unique=False)
    op.create_table('user_bets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=True),
    sa.Column('source_tipster_id', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('bookmaker', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('ret', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_tipster_id'], ['tipsters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bets_bookmaker'), 'user_bets', ['bookmaker'], unique=False)
    op.create_index(op.f('ix_user_bets_fixture_id'), 'user_bets', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_user_bets_market'), 'user_bets', ['market'], unique=False)
    op.create_index(op.f('ix_user_bets_placed_at'), 'user_bets', ['placed_at'], unique=False)
    op.create_index(op.f('ix_user_bets_user_id'), 'user_bets', ['user_id'], unique=False)
    op.create_index('ix_userbets_user_time', 'user_bets', ['user_id', 'placed_at'], unique=False)
    op.create_table('user_follows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tipster_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tipster_id'], ['tipsters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tipster_id', name='uq_user_follow')
    )
    op.create_index('ix_follow_user_tipster', 'user_follows', ['user_id', 'tipster_id'], unique=False)
    op.create_index(op.f('ix_user_follows_created_at'), 'user_follows', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_follows_tipster_id'), 'user_follows', ['tipster_id'], unique=False)
    op.create_index(op.f('ix_user_follows_user_id'), 'user_follows', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_follows_user_id'), table_name='user_follows')
    op.drop_index(op.f('ix_user_follows_tipster_id'), table_name='user_follows')
    op.drop_index(op.f('ix_user_follows_created_at'), table_name='user_follows')
    op.drop_index('ix_follow_user_tipster', table_name='user_follows')
    op.drop_table('user_follows')
    op.drop_index('ix_userbets_user_time', table_name='user_bets')
    op.drop_index(op.f('ix_user_bets_user_id'), table_name='user_bets')
    op.drop_index(op.f('ix_user_bets_placed_at'), table_name='user_bets')
    op.drop_index(op.f('ix_user_bets_market'), table_name='user_bets')
    op.drop_index(op.f('ix_user_bets_fixture_id'), table_name='user_bets')
    op.drop_index(op.f('ix_user_bets_bookmaker'), table_name='user_bets')
    op.drop_table('user_bets')
    op.drop_index(op.f('ix_tipster_subscriptions_user_id'), table_name='tipster_subscriptions')
    op.drop_index(op.f('ix_tipster_subscriptions_tipster_id'), table_name='tipster_subscriptions')
    op.drop_index(op.f('ix_tipster_subscriptions_started_at'), table_name='tipster_subscriptions')
    op.drop_index(op.f('ix_tipster_subscriptions_renews_at'), table_name='tipster_subscriptions')
    op.drop_index('ix_subs_status', table_name='tipster_subscriptions')
    op.drop_table('tipster_subscriptions')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index('ix_users_uid_email', table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
