"""fix CreatorPick FK to fixtures and BigInteger

Revision ID: 48c71ccd2b0d
Revises: 039b6cfcfd34
Create Date: 2025-11-04 20:41:11.313402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48c71ccd2b0d'
down_revision: Union[str, Sequence[str], None] = '039b6cfcfd34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('sport_focus', sa.String(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('roi_30d', sa.Float(), nullable=True),
    sa.Column('winrate_30d', sa.Float(), nullable=True),
    sa.Column('profit_30d', sa.Float(), nullable=True),
    sa.Column('picks_30d', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_username'), 'creator', ['username'], unique=True)
    op.create_table('creator_pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('bookmaker', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stake', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_pick_creator_id'), 'creator_pick', ['creator_id'], unique=False)
    op.create_index(op.f('ix_creator_pick_fixture_id'), 'creator_pick', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_creator_pick_market'), 'creator_pick', ['market'], unique=False)
    op.alter_column('expert_predictions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('expert_predictions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_expert_predictions_created_at'), 'expert_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_expert_predictions_updated_at'), 'expert_predictions', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expert_predictions_updated_at'), table_name='expert_predictions')
    op.drop_index(op.f('ix_expert_predictions_created_at'), table_name='expert_predictions')
    op.alter_column('expert_predictions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('expert_predictions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_creator_pick_market'), table_name='creator_pick')
    op.drop_index(op.f('ix_creator_pick_fixture_id'), table_name='creator_pick')
    op.drop_index(op.f('ix_creator_pick_creator_id'), table_name='creator_pick')
    op.drop_table('creator_pick')
    op.drop_index(op.f('ix_creator_username'), table_name='creator')
    op.drop_table('creator')
    # ### end Alembic commands ###
