"""premium featured picks

Revision ID: 5158371455f2
Revises: 0256e130d436
Create Date: 2025-11-22 00:56:57.457632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5158371455f2'
down_revision: Union[str, Sequence[str], None] = '0256e130d436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('featured_picks', sa.Column('is_premium_only', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('featured_picks', 'is_premium_only')
    # ### end Alembic commands ###
