"""fixture lockdown fixes

Revision ID: 53f5b9eb627e
Revises: 2cecefa30d7a
Create Date: 2025-12-09 10:33:36.353861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f5b9eb627e'
down_revision: Union[str, Sequence[str], None] = '2cecefa30d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture_views',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_views_created_at'), 'fixture_views', ['created_at'], unique=False)
    op.create_index(op.f('ix_fixture_views_fixture_id'), 'fixture_views', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_fixture_views_user_id'), 'fixture_views', ['user_id'], unique=False)
    op.create_index('ix_fixtureviews_fx_user', 'fixture_views', ['fixture_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fixtureviews_fx_user', table_name='fixture_views')
    op.drop_index(op.f('ix_fixture_views_user_id'), table_name='fixture_views')
    op.drop_index(op.f('ix_fixture_views_fixture_id'), table_name='fixture_views')
    op.drop_index(op.f('ix_fixture_views_created_at'), table_name='fixture_views')
    op.drop_table('fixture_views')
    # ### end Alembic commands ###
