"""tipster accas

Revision ID: 6058d239ec7e
Revises: 36a8d5b91acd
Create Date: 2025-11-05 22:37:49.162469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6058d239ec7e'
down_revision: Union[str, Sequence[str], None] = '36a8d5b91acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acca_legs', sa.Column('home_name', sa.String(), nullable=True))
    op.add_column('acca_legs', sa.Column('away_name', sa.String(), nullable=True))
    op.add_column('acca_tickets', sa.Column('source', sa.String(), nullable=False))
    op.add_column('acca_tickets', sa.Column('tipster_id', sa.Integer(), nullable=True))
    op.add_column('acca_tickets', sa.Column('result', sa.String(), nullable=True))
    op.add_column('acca_tickets', sa.Column('profit', sa.Float(), nullable=True))
    op.add_column('acca_tickets', sa.Column('settled_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_acca_tickets_tipster_id'), 'acca_tickets', ['tipster_id'], unique=False)
    op.create_foreign_key(None, 'acca_tickets', 'tipsters', ['tipster_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'acca_tickets', type_='foreignkey')
    op.drop_index(op.f('ix_acca_tickets_tipster_id'), table_name='acca_tickets')
    op.drop_column('acca_tickets', 'settled_at')
    op.drop_column('acca_tickets', 'profit')
    op.drop_column('acca_tickets', 'result')
    op.drop_column('acca_tickets', 'tipster_id')
    op.drop_column('acca_tickets', 'source')
    op.drop_column('acca_legs', 'away_name')
    op.drop_column('acca_legs', 'home_name')
    # ### end Alembic commands ###
