"""add stripe_price_id to tipsters

Revision ID: 613cf8f900ef
Revises: cae9dcd47b18
Create Date: 2025-11-25 21:04:22.013176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613cf8f900ef'
down_revision: Union[str, Sequence[str], None] = 'cae9dcd47b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipsters', sa.Column('stripe_price_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_tipsters_stripe_price_id'), 'tipsters', ['stripe_price_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipsters_stripe_price_id'), table_name='tipsters')
    op.drop_column('tipsters', 'stripe_price_id')
    # ### end Alembic commands ###
