"""featured emails

Revision ID: 784d82e88c1d
Revises: a9d0fd17e28c
Create Date: 2025-12-01 16:40:23.930673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784d82e88c1d'
down_revision: Union[str, Sequence[str], None] = 'a9d0fd17e28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_picks_opt_in', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_picks_opt_in')
    # ### end Alembic commands ###
