"""featured picks + nba models

Revision ID: 8823fd295c3d
Revises: 9dda19a01c39
Create Date: 2025-10-22 10:31:52.978277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8823fd295c3d'
down_revision: Union[str, Sequence[str], None] = '9dda19a01c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('featured_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('sport', sa.String(length=16), nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('blurb', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'fixture_id', name='uniq_pick_per_fixture_per_day')
    )
    op.create_index(op.f('ix_featured_picks_created_at'), 'featured_picks', ['created_at'], unique=False)
    op.create_index(op.f('ix_featured_picks_day'), 'featured_picks', ['day'], unique=False)
    op.create_index(op.f('ix_featured_picks_fixture_id'), 'featured_picks', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_featured_picks_is_public'), 'featured_picks', ['is_public'], unique=False)
    op.create_index(op.f('ix_featured_picks_sport'), 'featured_picks', ['sport'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_featured_picks_sport'), table_name='featured_picks')
    op.drop_index(op.f('ix_featured_picks_is_public'), table_name='featured_picks')
    op.drop_index(op.f('ix_featured_picks_fixture_id'), table_name='featured_picks')
    op.drop_index(op.f('ix_featured_picks_day'), table_name='featured_picks')
    op.drop_index(op.f('ix_featured_picks_created_at'), table_name='featured_picks')
    op.drop_table('featured_picks')
    # ### end Alembic commands ###
