"""add sport to Fixture

Revision ID: 989bd968f3f7
Revises: d495a47bad00
Create Date: 2025-09-17 19:48:36.706768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989bd968f3f7'
down_revision: Union[str, Sequence[str], None] = 'd495a47bad00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('sport', sa.String(), nullable=True))
    op.create_index(op.f('ix_fixtures_sport'), 'fixtures', ['sport'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixtures_sport'), table_name='fixtures')
    op.drop_column('fixtures', 'sport')
    # ### end Alembic commands ###
