"""welcome emails

Revision ID: a9d0fd17e28c
Revises: ec25cdaf8b42
Create Date: 2025-12-01 13:17:49.357543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d0fd17e28c'
down_revision: Union[str, Sequence[str], None] = 'ec25cdaf8b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('welcome_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'welcome_sent_at')
    # ### end Alembic commands ###
