"""global platform fee

Revision ID: b7f0911db297
Revises: 613cf8f900ef
Create Date: 2025-11-25 22:36:58.197310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f0911db297'
down_revision: Union[str, Sequence[str], None] = '613cf8f900ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipsters', sa.Column('rev_share_bps', sa.Integer(), server_default='1500', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipsters', 'rev_share_bps')
    # ### end Alembic commands ###
