"""sync models: featured picks comp + bigint fixes

Revision ID: bac55f49a36b
Revises: 9cf063a54cc1
Create Date: 2025-10-22 13:00:00.521455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bac55f49a36b'
down_revision: Union[str, Sequence[str], None] = '9cf063a54cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'bet_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.add_column('featured_picks', sa.Column('home_team', sa.String(), nullable=False))
    op.add_column('featured_picks', sa.Column('away_team', sa.String(), nullable=False))
    op.add_column('featured_picks', sa.Column('kickoff_utc', sa.DateTime(), nullable=False))
    op.add_column('featured_picks', sa.Column('market', sa.String(), nullable=False))
    op.add_column('featured_picks', sa.Column('bookmaker', sa.String(), nullable=False))
    op.add_column('featured_picks', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('featured_picks', sa.Column('edge', sa.Float(), nullable=True))
    op.add_column('featured_picks', sa.Column('note', sa.String(), nullable=True))
    op.alter_column('featured_picks', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('featured_picks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_featured_picks_is_public'), table_name='featured_picks')
    op.drop_constraint(op.f('uniq_pick_per_fixture_per_day'), 'featured_picks', type_='unique')
    op.create_index(op.f('ix_featured_picks_comp'), 'featured_picks', ['comp'], unique=False)
    op.create_index(op.f('ix_featured_picks_kickoff_utc'), 'featured_picks', ['kickoff_utc'], unique=False)
    op.create_index('ix_featuredpicks_day_sport', 'featured_picks', ['day', 'sport'], unique=False)
    op.create_unique_constraint('uq_featuredpicks_day_fx_mkt_book', 'featured_picks', ['day', 'fixture_id', 'market', 'bookmaker'])
    op.drop_column('featured_picks', 'is_public')
    op.drop_column('featured_picks', 'blurb')
    op.drop_column('featured_picks', 'title')
    op.alter_column('poll_votes', 'fixture_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poll_votes', 'fixture_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('featured_picks', sa.Column('title', sa.VARCHAR(length=160), autoincrement=False, nullable=True))
    op.add_column('featured_picks', sa.Column('blurb', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('featured_picks', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_featuredpicks_day_fx_mkt_book', 'featured_picks', type_='unique')
    op.drop_index('ix_featuredpicks_day_sport', table_name='featured_picks')
    op.drop_index(op.f('ix_featured_picks_kickoff_utc'), table_name='featured_picks')
    op.drop_index(op.f('ix_featured_picks_comp'), table_name='featured_picks')
    op.create_unique_constraint(op.f('uniq_pick_per_fixture_per_day'), 'featured_picks', ['day', 'fixture_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_featured_picks_is_public'), 'featured_picks', ['is_public'], unique=False)
    op.alter_column('featured_picks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('featured_picks', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('featured_picks', 'note')
    op.drop_column('featured_picks', 'edge')
    op.drop_column('featured_picks', 'price')
    op.drop_column('featured_picks', 'bookmaker')
    op.drop_column('featured_picks', 'market')
    op.drop_column('featured_picks', 'kickoff_utc')
    op.drop_column('featured_picks', 'away_team')
    op.drop_column('featured_picks', 'home_team')
    op.alter_column('alerts', 'bet_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
