"""tipster acca updates

Revision ID: cae9dcd47b18
Revises: 14681aede4f1
Create Date: 2025-11-25 20:45:53.435562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae9dcd47b18'
down_revision: Union[str, Sequence[str], None] = '14681aede4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acca_tickets', sa.Column('is_premium_only', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('acca_tickets', sa.Column('is_subscriber_only', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acca_tickets', 'is_subscriber_only')
    op.drop_column('acca_tickets', 'is_premium_only')
    # ### end Alembic commands ###
