"""Add duplicate_alert_hash to bets

Revision ID: cb01020286e0
Revises: 
Create Date: 2025-08-31 14:28:08.319018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb01020286e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('duplicate_alert_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_bets_duplicate_alert_hash'), 'bets', ['duplicate_alert_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_duplicate_alert_hash'), table_name='bets')
    op.drop_column('bets', 'duplicate_alert_hash')
    # ### end Alembic commands ###
