"""Add referee and venue to fixtures

Revision ID: d495a47bad00
Revises: 16801b8cbd2a
Create Date: 2025-09-17 16:35:37.117568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd495a47bad00'
down_revision: Union[str, Sequence[str], None] = '16801b8cbd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('referee', sa.String(), nullable=True))
    op.add_column('fixtures', sa.Column('venue', sa.String(), nullable=True))
    op.add_column('fixtures', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixtures', 'city')
    op.drop_column('fixtures', 'venue')
    op.drop_column('fixtures', 'referee')
    # ### end Alembic commands ###
