"""tipster acca fixes adding in team names

Revision ID: dd07485cc5f8
Revises: fe244c5f3601
Create Date: 2025-11-06 11:43:17.879229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd07485cc5f8'
down_revision: Union[str, Sequence[str], None] = 'fe244c5f3601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acca_legs', sa.Column('home_name', sa.String(), nullable=True))
    op.add_column('acca_legs', sa.Column('away_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acca_legs', 'away_name')
    op.drop_column('acca_legs', 'home_name')
    # ### end Alembic commands ###
