"""rename creator to tipster models

Revision ID: e54eb258fc75
Revises: 48c71ccd2b0d
Create Date: 2025-11-04 21:19:39.717298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e54eb258fc75'
down_revision: Union[str, Sequence[str], None] = '48c71ccd2b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('sport_focus', sa.String(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('roi_30d', sa.Float(), nullable=True),
    sa.Column('winrate_30d', sa.Float(), nullable=True),
    sa.Column('profit_30d', sa.Float(), nullable=True),
    sa.Column('picks_30d', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipsters_username'), 'tipsters', ['username'], unique=True)
    op.create_table('tipster_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipster_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('bookmaker', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stake', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipster_id'], ['tipsters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipster_picks_fixture_id'), 'tipster_picks', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_tipster_picks_market'), 'tipster_picks', ['market'], unique=False)
    op.create_index(op.f('ix_tipster_picks_tipster_id'), 'tipster_picks', ['tipster_id'], unique=False)
    op.drop_index(op.f('ix_creator_pick_creator_id'), table_name='creator_pick')
    op.drop_index(op.f('ix_creator_pick_fixture_id'), table_name='creator_pick')
    op.drop_index(op.f('ix_creator_pick_market'), table_name='creator_pick')
    op.drop_table('creator_pick')
    op.drop_index(op.f('ix_creator_username'), table_name='creator')
    op.drop_table('creator')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('creator_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sport_focus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('social_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('join_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('roi_30d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('winrate_30d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('profit_30d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('picks_30d', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='creator_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_creator_username'), 'creator', ['username'], unique=True)
    op.create_table('creator_pick',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fixture_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('market', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bookmaker', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stake', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], name=op.f('creator_pick_creator_id_fkey')),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], name=op.f('creator_pick_fixture_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('creator_pick_pkey'))
    )
    op.create_index(op.f('ix_creator_pick_market'), 'creator_pick', ['market'], unique=False)
    op.create_index(op.f('ix_creator_pick_fixture_id'), 'creator_pick', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_creator_pick_creator_id'), 'creator_pick', ['creator_id'], unique=False)
    op.drop_index(op.f('ix_tipster_picks_tipster_id'), table_name='tipster_picks')
    op.drop_index(op.f('ix_tipster_picks_market'), table_name='tipster_picks')
    op.drop_index(op.f('ix_tipster_picks_fixture_id'), table_name='tipster_picks')
    op.drop_table('tipster_picks')
    op.drop_index(op.f('ix_tipsters_username'), table_name='tipsters')
    op.drop_table('tipsters')
    # ### end Alembic commands ###
